import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/app/components/Sidebar";
import MusicPlayer from "@/app/components/MusicPlayer";

export const metadata: Metadata = {
  title: "Exercise 2-3, Kyaw Kyaw Oo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <div className='h-screen flex flex-col justify-between'>
          <Sidebar>{children}</Sidebar>
          <MusicPlayer />
        </div>
      </body>
    </html>
  );
}
