export type TAllTrackResposne = {
  track: TTrack[];
};

export type TAllAlubmResponse = {
  album: Album[];
};

export type TTrack = {
  idTrack: string;
  idAlbum: string;
  idArtist: string;
  idLyric: string;
  idIMVDB: string | null;
  strTrack: string;
  strAlbum: string;
  strArtist: string;
  strArtistAlternate: string | null;
  intCD: string | null;
  intDuration: string;
  strGenre: string;
  strMood: string | null;
  strStyle: string | null;
  strTheme: string | null;
  strDescriptionEN?: string;
  strDescriptionDE: string | null;
  strDescriptionFR: string | null;
  strDescriptionCN: string | null;
  strDescriptionIT: string | null;
  strDescriptionJP: string | null;
  strDescriptionRU: string | null;
  strDescriptionES: string | null;
  strDescriptionPT: string | null;
  strDescriptionSE: string | null;
  strDescriptionNL: string | null;
  strDescriptionHU: string | null;
  strDescriptionNO: string | null;
  strDescriptionIL: string | null;
  strDescriptionPL: string | null;
  strTrackThumb: string | null;
  strTrack3DCase: string | null;
  strTrackLyrics?: string;
  strMusicVid?: string;
  strMusicVidDirector: string | null;
  strMusicVidCompany: string | null;
  strMusicVidScreen1: string | null;
  strMusicVidScreen2: string | null;
  strMusicVidScreen3: string | null;
  intMusicVidViews: string | null;
  intMusicVidLikes: string | null;
  intMusicVidDislikes: string | null;
  intMusicVidFavorites: string | null;
  intMusicVidComments: string | null;
  intTrackNumber: string;
  intLoved: string;
  intScore: string | null;
  intScoreVotes: string | null;
  intTotalListeners: string | null;
  intTotalPlays: string | null;
  strMusicBrainzID: string;
  strMusicBrainzAlbumID: string;
  strMusicBrainzArtistID: string;
  strLocked: string;
};

type Album = {
  idAlbum: string;
  idArtist: string;
  idLabel?: string;
  strAlbum: string;
  strAlbumStripped: string;
  strArtist: string;
  strArtistStripped: string;
  intYearReleased: string;
  strStyle?: string;
  strGenre?: string;
  strLabel?: string;
  strReleaseFormat: string;
  intSales: string;
  strAlbumThumb?: string;
  strAlbumThumbHQ: string | null;
  strAlbumBack?: string;
  strAlbumCDart?: string;
  strAlbumSpine?: string;
  strAlbum3DCase?: string;
  strAlbum3DFlat?: string;
  strAlbum3DFace?: string;
  strAlbum3DThumb?: string;
  strDescriptionEN?: string;
  strDescriptionDE: string | null;
  strDescriptionFR?: string;
  strDescriptionCN: string | null;
  strDescriptionIT: string | null;
  strDescriptionJP: string | null;
  strDescriptionRU: string | null;
  strDescriptionES?: string;
  strDescriptionPT: string | null;
  strDescriptionSE: string | null;
  strDescriptionNL: string | null;
  strDescriptionHU: string | null;
  strDescriptionNO: string | null;
  strDescriptionIL: string | null;
  strDescriptionPL: string | null;
  intLoved?: string;
  intScore?: string;
  intScoreVotes?: string;
  strReview?: string;
  strMood?: string;
  strTheme?: string;
  strSpeed?: string;
  strLocation: string | null;
  strMusicBrainzID: string;
  strMusicBrainzArtistID: string;
  strAllMusicID?: string;
  strBBCReviewID?: string;
  strRateYourMusicID?: string;
  strDiscogsID?: string;
  strWikidataID?: string;
  strWikipediaID?: string;
  strGeniusID?: string;
  strLyricWikiID: string | null;
  strMusicMozID: string | null;
  strItunesID: string | null;
  strAmazonID: string | null;
  strLocked: string;
  strDescription: string | null;
};
